### ISSUE TITLE
Approach for providing secrets to tasks

### ISSUE THREAD

**Issue by piotr-kalanski** [piotr-kalanski/service-initializer#16]

**Comment by piotr-kalanski** [comment]
Przekazywanie poprzez environment variables

**Comment by piotr-kalanski** [comment]
Podanie nazwy secret przy parametrze np.:

```yaml
steps:
   - name: Create github repository 
     task:
        type: Github_CreateRepository
        parameters:
           - oauth_token: {secret:GITHUB_TOKEN} 
```

**Comment by piotr-kalanski** [comment]
Alternatywnie odczyt z jakiegoś pliku

**Comment by piotr-kalanski** [comment]
Klasa secrets reader

**Comment by piotr-kalanski** [comment]
```yaml
secrets:
   environment:
      - secret_name1: ENV_VAR_NAME1
      - secret_name2: ENV_VAR_NAME2
   files:
      - /dir1/dir2/secrets.yaml

steps:
   - name: Create github repository 
     task:
        type: Github_CreateRepository
        parameters:
           - oauth_token: {secret:GITHUB_TOKEN} 
```
